### PR TITLE
Marquee guide

### PR DESCRIPTION
**Pull request by teunbrand**
Hi Thomas,

This is my proposal for a marquee guide.
Instead of going into details, I'll render the examples which are hopefully somewhat self-expanatory.
Please let me know if you'd wish to change some things.

``` r
library(ggplot2)
library(marquee)
# A standard plot
base <- ggplot(mpg, aes(displ, hwy)) +
  geom_point()

# Using key glyphs
base + aes(shape = drv) +
  scale_shape_discrete(
    # Same as using <<1>>, <<2>> and <<3>>,
    # or ![](1), ![](2) and ![](3)
    # or ![](4), ![](f) and ![](r)
    name = "Cars with four wheel <<4>>, forward <<f>> or reverse <<r>> drive.",
    guide = "marquee"
  )
```

``` r
# Recolouring text
base <- base +
  aes(colour = drv) +
  labs(
    colour = "Cars with {.4 four wheel}, {.f forward} or {.r reverse} drive."
  )
base + guides(colour = "marquee")
```

``` r
# Adjust display of labels
st <- style(weight = "bold", italic = TRUE, background = NA)
base + guides(colour = guide_marquee(style = st))
```

``` r
# Using background instead of text colour by setting it to NULL
st <- style(color = "black", background = NULL)
base + guides(colour = guide_marquee(style = st))
```

``` r
# Customising style of each label through style sets
# Note: tag names must be universal per `vctrs::vec_as_names` and
# prefixed with `lab_`.
st <- classic_style()
st <- modify_style(st, tag = "lab_f", background = NULL, color = "black")
st <- modify_style(st, tag = "lab_r", border_size = trbl(1),
                   color = "black", background = NA)
base + guides(colour = guide_marquee(style = st))
```

``` r
# Alternatively:
base + guides(colour = "marquee") +
  theme(plot.subtitle = element_marquee(style = st))
```

``` r
# Splicing in labels
base + aes(colour = class) +
  labs(colour = "Cars including !!2 and !!6 vehicles") +
  guides(colour = "marquee")
```

``` r
# Using automatic detection
base + aes(colour = class) +
  labs(colour = "Cars including suv and minivan vehicles") +
  guides(colour = guide_marquee(detect = TRUE))
```

``` r
# Automatic detection is not always a good idea
base +
  labs(colour = "Kerfuffles 4 the riffraff from frankfurt") +
  guides(colour = guide_marquee(detect = TRUE))
```

<sup>Created on 2024-06-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by thomasp85** [comment]
This looks very promising. Some thoughts:

* I think the automatic detection can focus on whole words so as to avoid the last example. I can't see when it would ever be useful not want it to detect full words
* breaks can include spaces while marquee classes cannot. How is this handled?
* How can this be combined with a regular legend? If possible at all?
* It's not clear how the splicing in of labels happens. What are `2` and `6` referring to?

**Comment by teunbrand** [comment]
> I think the automatic detection can focus on whole words so as to avoid the last example. I can't see when it would ever be useful not want it to detect full words

I'll look into finding the right regex incantation for this.

> breaks can include spaces while marquee classes cannot. How is this handled?

Through the `repair = "universal"` in `vec_as_names()` for class names. It ensures the tag is both syntactic and unique.

``` r
x <- "I'm displaying spaces."
tolower(vctrs::vec_as_names(x, repair = "universal", quiet = TRUE))
#> [1] "i.m.displaying.spaces."
```

<sup>Created on 2024-06-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

> How can this be combined with a regular legend? If possible at all?

It cannot, I don't think you can have >1 guide per aesthetic in ggplot2.
You can hack it of course by using a guide for a different aesthetic with the same mapping and using `override.aes` to emulate the original aesthetic.

> It's not clear how the splicing in of labels happens. What are 2 and 6 referring to?

Using `!!n` will insert the `n`<sup>th</sup> label, so `!!2` and `!!6` will insert the 2<sup>nd</sup> and 6<sup>th</sup> label. 
It would be the same as `"Cars including !!compact and !!subcompact vehicles"`. Perhaps the example should mix the two ways to showcase them both. This pattern is included in the 'text formatting' section of the docs.

**Comment by thomasp85** [comment]
Ok, let's merge this in and take it for a spin. Can you add a topic to the pkgdown site so that doesn't fail

**Comment by teunbrand** [comment]
Gotcha

**Comment by thomasp85** [comment]
Thank you

**Comment by teunbrand** [comment]
Just because I notice you gearing up for a new {marquee} release: I forgot to include a news bullet, but it probably should have one in the upcoming release

**Pull request merged**
